postgres-dev:
  image: postgres
  environment:
    PORT: 5432
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: postgres
  ports:
    - '5432:5432'
  expose:
    - "5432"

web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  links: 
    - postgres-dev
  environment:
    PORT: 8080
  ports:
    - '8080:8080'

shell:
  build: .
  command: bash
  working_dir: /app/user
  links:
    - postgres-dev
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
